version: "3"
services:
  dev:
    container_name: angapp
    build: .
    ports:
      - "4200:4200" 
    environment:
      SHELL: /bin/bash
      NODE_ENV: development
    volumes:
      - ~/.gitconfig:/etc/gitconfig
      - ./src:/angapp/src:cached
      - ./e2e:/angapp/e2e:cached
      - ./tsconfig.json:/angapp/tsconfig.json
      - ./tslint.json:/angapp/tslint.json
      - ./package.json:/angapp/package.json
      - ./angular.json:/angapp/angular.json
    entrypoint: ng serve --host 0.0.0.0
